### ISSUE TITLE
SW 5.4.* : frosh:export:mails missing from command list

### ISSUE THREAD

**Issue by RobertLang** [FriendsOfShopware/FroshTemplateMail#12]
### PHP Version

PHP 7.4

### Shopware Version

Shopware 5.7.*

### Actual behaviour

The console command `frosh:export:mails` doesn't show up when calling `bin/console` in Shopware 5.7.*

This can be fixed by adding the command name to the service definition in `FroshTemplateMail/Resources/services.xml` line 17-19:

 ```
        <service id="frosh_template_mail.command.export" class="FroshTemplateMail\Commands\ExportMailTemplatesCommand">
            <tag name="console.command"  command="frosh:export:mails"/>
        </service>
```

### Expected behaviour

The console command `frosh:export:mails` should be in the command list when calling `bin/console`.

### Steps to Reproduce?

Install the latest plugin version to a Shopware 5.4.* shop, activate it and check if the comsole command shows up.

**Comment by shyim** [comment]
Can you make a PR?

**Comment by shyim** [comment]
seems like fixedf with https://github.com/shopware/shopware/commit/e967decd1ba0053172204f9416ecbfa2ea90b733
