### ISSUE TITLE
Text emails not supported?

### ISSUE THREAD

**Issue by cm-springlane** [FriendsOfShopware/FroshTemplateMail#5]
## Actual behaviour

    If I uncheck "send as HTML mail" in the backend the mail is still sent as an HTML mail.

## Expected behaviour

    I expect to get a plaintext mail.

## Environment

    Shopware 5.4.5

## Steps to reproduce

1. Create mail templates in theme
2. Uncheck 'send as HTML mail', save, clear cache
3. Click on 'send test mail' OR trigger the sending of the mail in the frontend

## Checklist

- [X ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshTemplateMail/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ X] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Hmm
https://github.com/FriendsOfShopware/FroshTemplateMail/blob/master/Components/TemplateMailLoader.php#L74

setIsHtml is only triggered if a html template is also available. Is the file existing in your directory?

**Comment by shyim** [comment]
Is this Problem still there?

**Comment by cm-springlane** [comment]
Hi Shyim, I'm sorry, I didn't get any gitlab emails with your comments and forgot to check back.

The problem still exists but I think you might have misinterpreted it. I can't get text emails - html works fine. There's a checkbox in the backend "vorlage als html versenden" but if I leave it unchecked I still get html mails.

I know I can remove the reference to the html template, but that's a PITA just to check if the text email is all right for people who do actually get it as a fallback.

I realize this is super low importance, buuut it does break existing shopware functionality so I thought I'd flag it.

**Comment by shyim** [comment]
The existence of the files overriding the template mail settings. So if you have a html file, the checkbox will be checked.

**Comment by cm-springlane** [comment]
Mm, ok.
