### ISSUE TITLE
Error when updating to 5.5.

### ISSUE THREAD

**Issue by cm-springlane** [FriendsOfShopware/FroshTemplateMail#7]
---

## Actual behaviour

I get this error when updating Shopware to 5.5.: 

PHP Fatal error:  Uncaught Error: Call to undefined method FroshTemplateMail\Commands\ExportMailTemplatesCommand::getDefaultName() in /var/www/spl-platform/htdocs/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php:61
Stack trace:
#0 /var/www/spl-platform/htdocs/vendor/symfony/dependency-injection/Compiler/Compiler.php(141): Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /var/www/spl-platform/htdocs/vendor/symfony/dependency-injection/ContainerBuilder.php(790): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /var/www/spl-platform/htdocs/engine/Shopware/Kernel.php(563): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /var/www/spl-platform/htdocs/engine/Shopware/Kernel.php(304): Shopware\Kernel->initializeContainer()
#4 /var/www/spl-platform/htdocs/recovery/update/src/DependencyInjection/Container.php(180): Shopwa in /var/www/spl-platform/htdocs/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php on line 61

## Expected behaviour

No error occurs

## Environment
Updating from 5.4.5 to newest 5.5.(I think 6)

## Steps to reproduce

Update to 5.5 with this plugin installed

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshTemplateMail/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by shyim** [comment]
Already known issue. Its fixed with Shopware 5.5.7. Disable the plugin in Update

**Comment by cm-springlane** [comment]
Wonderful, thanks
