### ISSUE TITLE
Problem after updating to Version 1.1.0

### ISSUE THREAD

**Issue by cm-springlane** [FriendsOfShopware/FroshTemplateMail#9]
## Actual behaviour

    After updating to Plugin Version 1.1.0 emails from our shop springlane.de sometimes had the sender and subject that are configured for burnhard.de and also sometimes the other way around. The mail content was correct in all cases that we checked except for one case in which a mail from burnhard.de contained the text from burnhard.nl (so it might be two separate bugs? we don't know).

## Expected behaviour

    Emails from a shop/subshop should always have the correct sender, subject and content

## Environment

    Shopware 5.5.10, php 7.2.29, running on nginx

## Steps to reproduce

1. Update to 1.1.0
2. Have lots of customers all ordering at the same time in different shops -- we assume, because we couldn't reproduce it on our dev machines

## Checklist

- [x] I have checked [all issues](https://github.com/FriendsOfShopware/FroshTemplateMail/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ ] I am using the latest stable version of this plugin.

**Comment by shyim** [comment]
Are you sure that you don't had problems in earlier versions? The changes are only doing compatible changes https://github.com/FriendsOfShopware/FroshTemplateMail/compare/1.0.2...1.1.0

**Comment by cm-springlane** [comment]
We reverted to 1.0.0 and it works.

**Comment by cm-springlane** [comment]
Just because we reverted to the previous version doesn't mean the issue was fixed, though.
